dist: xenial
language: rust
rust:
    - stable
before_script:
    - rustup update
    - rustup component add clippy
    - rustup component add rustfmt
script:
    - cargo test --all
    - cargo fmt --all -- --check
    - cargo clippy --all
